[package]
name = "dlp-storage"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
dlp-crypto = { path = "../dlp-crypto" }
dlp-domain = { path = "../dlp-domain" }
sha2 = "=0.10.9"

[dev-dependencies]
tempfile = "=3.27.0"
