[package]
name = "dlp-windows-drive"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
dlp-storage = { path = "../dlp-storage" }
winfsp = "0.13.0"

[build-dependencies]
winfsp = "0.13.0"

[dev-dependencies]
dlp-domain = { path = "../dlp-domain" }
