[package]
name = "dlp-server"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
axum = "=0.8.9"
dlp-crypto = { path = "../dlp-crypto" }
dlp-domain = { path = "../dlp-domain" }
dlp-protocol = { path = "../dlp-protocol" }
ldap3 = { version = "=0.11.5", default-features = false, features = ["tls-rustls"] }
rcgen = { version = "=0.14.8", features = ["pem", "x509-parser"] }
rustls = { version = "=0.23.43", default-features = false, features = ["std", "ring", "tls12", "logging"] }
serde = { version = "=1.0.229", features = ["derive"] }
sha2 = "=0.11.0"
sqlx = { version = "=0.9.0", default-features = false, features = ["migrate", "macros", "postgres", "runtime-tokio", "tls-rustls-ring"] }
tokio = { version = "=1.53.1", features = ["macros", "net", "rt-multi-thread", "time"] }
tokio-rustls = { version = "=0.26.4", default-features = false, features = ["ring", "tls12", "logging"] }
uuid = { version = "=1.24.0", features = ["v4"] }
x509-parser = "=0.18.1"

[[test]]
name = "server_enrollment"
path = "../../tests/e2e/server_enrollment.rs"

[[test]]
name = "compose"
path = "../../tests/e2e/compose.rs"
