[CmdletBinding(SupportsShouldProcess)]
param([Parameter(Mandatory)][string]$ClosurePath,[Parameter(Mandatory)][string[]]$ThreatId,[string]$SignerThumbprint,[string]$ReviewerPolicyPath,[switch]$DryRun,[string]$PublicationBarrierPath,[switch]$CrashBeforeReplace)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
try{Add-Type -AssemblyName System.Security -ErrorAction Stop}catch{throw 'pkcs_runtime_unavailable'}
function HashText($v){$s=[Security.Cryptography.SHA256]::Create();try{$j=$v|ConvertTo-Json -Depth 20 -Compress;$b=[Text.UTF8Encoding]::new($false).GetBytes(($j-replace"`r`n","`n"));([BitConverter]::ToString($s.ComputeHash($b))).Replace('-','').ToLowerInvariant()}finally{$s.Dispose()}}
function HashFile($p){$s=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($s.ComputeHash([IO.File]::ReadAllBytes((Resolve-Path -LiteralPath $p))))).Replace('-','').ToLowerInvariant()}finally{$s.Dispose()}}
function Payload($r){[ordered]@{threat_id=[string]$r.threat_id;disposition=[string]$r.disposition;severity=[string]$r.severity;mitigation_assertion=[string]$r.mitigation_assertion;implementation_refs=@($r.implementation_refs|%{[ordered]@{path=[string]$_.path;sha256=[string]$_.sha256}});evidence_attempt_ids=@($r.evidence_attempt_ids|%{[string]$_});required_machine_roles=@($r.required_machine_roles|%{[string]$_});artifact_refs=@($r.artifact_refs|%{[ordered]@{path=[string]$_.path;sha256=[string]$_.sha256;role=[string]$_.role}});procedure_version=[string]$r.procedure_version;environment_fingerprint=$r.environment_fingerprint}}
function Body($a){[ordered]@{threat_id=[string]$a.threat_id;payload_digest=[string]$a.payload_digest;reviewer_identity=$a.reviewer_identity;review_utc=[string]$a.review_utc;procedure_version=[string]$a.procedure_version;environment_fingerprint=$a.environment_fingerprint;previous_attestation_digest=[string]$a.previous_attestation_digest}}
function Sign-Body($body,$cert){$bytes=[Text.UTF8Encoding]::new($false).GetBytes((($body|ConvertTo-Json -Depth 20 -Compress)-replace"`r`n","`n"));$cms=[Security.Cryptography.Pkcs.SignedCms]::new([Security.Cryptography.Pkcs.ContentInfo]::new($bytes),$true);$signer=[Security.Cryptography.Pkcs.CmsSigner]::new($cert);$signer.IncludeOption='EndCertOnly';$cms.ComputeSignature($signer);[Convert]::ToBase64String($cms.Encode())}
function Get-PublicationMutexName([string]$Path){'Global\DlpPhase1SecurityClosure-'+(HashText ([IO.Path]::GetFullPath($Path).ToUpperInvariant()))}
function Get-CurrentUserSigner([string]$Thumbprint){$store=[Security.Cryptography.X509Certificates.X509Store]::new('My',[Security.Cryptography.X509Certificates.StoreLocation]::CurrentUser);try{$store.Open([Security.Cryptography.X509Certificates.OpenFlags]::ReadOnly);$matches=@($store.Certificates|Where-Object {($_.Thumbprint-replace'\s','')-eq($Thumbprint-replace'\s','')});if($matches.Count-ne1){throw 'signer_thumbprint_match_count_invalid'};$matches[0]}finally{$store.Dispose()}}
$ClosurePath=(Resolve-Path -LiteralPath $ClosurePath).Path;$initial=Get-Content -Raw -LiteralPath $ClosurePath|ConvertFrom-Json;if($initial.schema_version-ne'phase1-security-closure/v2'){throw 'v2 closure required'}
$policy=$null;$cert=$null;$reviewer=$null;$observedIdentity=$null;$observedMachine=$null
if(!$DryRun-and$PSCmdlet.ShouldProcess($ClosurePath,'publish signed security closure review')){if(!$ReviewerPolicyPath-or!(Test-Path -LiteralPath $ReviewerPolicyPath)){throw 'ReviewerPolicyPath is required.'};$policy=Get-Content -Raw -LiteralPath $ReviewerPolicyPath|ConvertFrom-Json;if(!$SignerThumbprint){throw 'SignerThumbprint is required.'};$cert=Get-CurrentUserSigner $SignerThumbprint;if(!$cert.HasPrivateKey){throw 'Selected CurrentUser signer certificate with private key was not found.'};$reviewers=@($policy.reviewers|?{([string]$_.thumbprint-replace'\s','')-eq($cert.Thumbprint-replace'\s','')});if($reviewers.Count-ne1){throw 'reviewer_policy_match_count_invalid'};$reviewer=$reviewers[0];$observedIdentity=[Security.Principal.WindowsIdentity]::GetCurrent().Name;$observedMachine=[string]$env:COMPUTERNAME;if(![string]::Equals($observedIdentity,[string]$reviewer.identity,[StringComparison]::OrdinalIgnoreCase)){throw 'reviewer_identity_mismatch'};if(![string]::Equals($observedMachine,[string]$reviewer.machine_identity,[StringComparison]::OrdinalIgnoreCase)){throw 'reviewer_machine_mismatch'}}
$approved=@{}
foreach($tid in $ThreatId){$r=@($initial.records|? threat_id -eq $tid);if($r.Count-ne1){throw "Unknown or duplicate threat ID: $tid"};$payload=Payload $r[0];$pd=HashText $payload;$prior=@($r[0].attestations)|Select-Object -Last 1;$preview=[ordered]@{protected_payload=$payload;resolved_payload_digest=$pd;proposed_attestation=[ordered]@{threat_id=$tid;payload_digest=$pd;reviewer_identity=if($cert){[ordered]@{kind='independent_verifier';name=$observedIdentity}}else{'dry-run'};review_utc='<publication-time>';procedure_version=if($policy){$policy.procedure_version}else{'dry-run'};environment_fingerprint=[ordered]@{machine_identity=if($cert){$observedMachine}else{$env:COMPUTERNAME};role=if($reviewer){$reviewer.role}else{'dry-run'};domain_network_identity=if($reviewer){$reviewer.domain_network_identity}else{'dry-run'}};previous_attestation_digest=if($prior){[string]$prior.attestation_digest}else{''}};signer_certificate=if($cert){[ordered]@{subject=$cert.Subject;thumbprint=$cert.Thumbprint}}else{'dry-run'};trust_policy_identity=if($ReviewerPolicyPath-and(Test-Path $ReviewerPolicyPath)){HashFile $ReviewerPolicyPath}else{'dry-run'}};Write-Host ($preview|ConvertTo-Json -Depth 20)
 if(!$DryRun-and$PSCmdlet.ShouldProcess($tid,'affirm exact protected payload')){$answer=Read-Host "Attest exact complete payload ${tid}? Type YES";if($answer-ne'YES'){throw "Review declined for $tid"};$approved[$tid]=[ordered]@{payload_digest=$pd;previous_attestation_digest=if($prior){[string]$prior.attestation_digest}else{''}}}}
if($DryRun-or!$PSCmdlet.ShouldProcess($ClosurePath,'write signed attestations')){Write-Host 'Dry-run/WhatIf valid: no manifest changes published.';exit 0}
$mutexName=Get-PublicationMutexName $ClosurePath;$mutex=[Threading.Mutex]::new($false,$mutexName);$held=$false;$tmp=$null
try{if(!$mutex.WaitOne([TimeSpan]::FromSeconds(30))){throw 'publication_conflict'};$held=$true;if($PublicationBarrierPath){[IO.File]::WriteAllText($PublicationBarrierPath,'locked');while(Test-Path "$PublicationBarrierPath.wait"){Start-Sleep -Milliseconds 25}}
 $closure=Get-Content -Raw -LiteralPath $ClosurePath|ConvertFrom-Json
 foreach($tid in $ThreatId){if(!$approved[$tid]){throw "affirmation_missing:$tid"};$r=@($closure.records|? threat_id -eq $tid);if($r.Count-ne1){throw "publication_conflict:$tid"};$pd=HashText (Payload $r[0]);$prior=@($r[0].attestations)|Select-Object -Last 1;$priorDigest=if($prior){[string]$prior.attestation_digest}else{''};$approvedPayloadDigest=[string]$approved[$tid]['payload_digest'];$approvedPriorDigest=[string]$approved[$tid]['previous_attestation_digest'];if($pd-ne$approvedPayloadDigest-or$priorDigest-ne$approvedPriorDigest){throw "publication_conflict:$tid"};$a=[ordered]@{threat_id=$tid;payload_digest=$pd;reviewer_identity=[ordered]@{kind='independent_verifier';name=$observedIdentity};review_utc=[DateTime]::UtcNow.ToString('o',[Globalization.CultureInfo]::InvariantCulture);procedure_version=[string]$policy.procedure_version;environment_fingerprint=[ordered]@{machine_identity=$observedMachine;role=[string]$reviewer.role;domain_network_identity=[string]$reviewer.domain_network_identity};previous_attestation_digest=$priorDigest};$a.attestation_digest=HashText (Body $a);$a.signature_cms_base64=Sign-Body (Body $a) $cert;$r[0].attestations=@($r[0].attestations)+@([pscustomobject]$a)}
 $tmp=Join-Path (Split-Path $ClosurePath) ('.'+[IO.Path]::GetFileName($ClosurePath)+'.'+[guid]::NewGuid().ToString('N')+'.tmp');$bytes=[Text.UTF8Encoding]::new($false).GetBytes(($closure|ConvertTo-Json -Depth 20));$stream=[IO.File]::Open($tmp,'CreateNew','Write','None');try{$stream.Write($bytes,0,$bytes.Length);$stream.Flush($true)}finally{$stream.Dispose()};if($CrashBeforeReplace){throw 'injected_crash_before_replace'};$backup="$tmp.bak";[IO.File]::Replace($tmp,$ClosurePath,$backup,$true);Remove-Item $backup -Force -ErrorAction SilentlyContinue;$tmp=$null
}finally{if($tmp){Remove-Item $tmp -Force -ErrorAction SilentlyContinue};if($held){$mutex.ReleaseMutex()};$mutex.Dispose()}
