[CmdletBinding(SupportsShouldProcess)]
param([Parameter(Mandatory)][string]$ClosurePath,[Parameter(Mandatory)][string[]]$ThreatId,[switch]$DryRun,[switch]$ConfirmEach)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
function HashText($v){$s=[Security.Cryptography.SHA256]::Create();try{$j=$v|ConvertTo-Json -Depth 20 -Compress;$b=[Text.UTF8Encoding]::new($false).GetBytes(($j-replace"`r`n","`n"));([BitConverter]::ToString($s.ComputeHash($b))).Replace('-','').ToLowerInvariant()}finally{$s.Dispose()}}
function HashFile($p){$s=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($s.ComputeHash([IO.File]::ReadAllBytes((Resolve-Path $p))))).Replace('-','').ToLowerInvariant()}finally{$s.Dispose()}}
function Payload($r){[ordered]@{threat_id=[string]$r.threat_id;disposition=[string]$r.disposition;severity=[string]$r.severity;mitigation_assertion=[string]$r.mitigation_assertion;implementation_refs=@($r.implementation_refs|%{[ordered]@{path=[string]$_.path;sha256=[string]$_.sha256}});evidence_attempt_ids=@($r.evidence_attempt_ids|%{[string]$_});required_machine_roles=@($r.required_machine_roles|%{[string]$_});artifact_refs=@($r.artifact_refs|%{[ordered]@{path=[string]$_.path;sha256=[string]$_.sha256;role=[string]$_.role}});procedure_version=[string]$r.procedure_version;environment_fingerprint=$r.environment_fingerprint}}
$identity=[Security.Principal.WindowsIdentity]::GetCurrent().Name
$machine=$env:COMPUTERNAME
if([string]::IsNullOrWhiteSpace($identity)-or$identity-notmatch'^[^\\]+\\[^\\]+$'){throw 'Authenticated domain-qualified reviewer identity is required.'}
if($machine-eq'hungdinh-lt'-or$identity-match'(?i)^hungdinh-lt\\'){throw 'Independent closure review must run in the authenticated lab/domain context, not hungdinh-lt.'}
$before=HashFile $ClosurePath;$closure=Get-Content -Raw $ClosurePath|ConvertFrom-Json;if($closure.schema_version-ne'phase1-security-closure/v2'){throw 'v2 closure required'}
foreach($tid in $ThreatId){$r=@($closure.records|? threat_id -eq $tid);if($r.Count-ne1){throw"Unknown or duplicate threat ID: $tid"};$r=$r[0];$pd=HashText (Payload $r);Write-Host(($r|Select-Object threat_id,mitigation_assertion,implementation_refs,artifact_refs,payload_digest|ConvertTo-Json -Depth 10));if($ConfirmEach-and!$DryRun){$answer=Read-Host "Attest exact payload ${tid}? Type YES";if($answer-ne'YES'){throw"Review declined for $tid"}};$prior=@($r.attestations)|Select-Object -Last 1;$body=[ordered]@{threat_id=$tid;payload_digest=$pd;reviewer_identity=[ordered]@{kind='authenticated_domain_operator';name=$identity};review_utc=[DateTime]::UtcNow.ToString('o',[Globalization.CultureInfo]::InvariantCulture);procedure_version='01-28/v2';environment_fingerprint=[ordered]@{machine_identity=$machine;role='independent_reviewer';domain_network_identity=($identity-split'\\')[0]};previous_attestation_digest=if($prior){[string]$prior.attestation_digest}else{''}};$body.attestation_digest=HashText $body;if(!$DryRun){$r.attestations=@($r.attestations)+@([pscustomobject]$body)}}
if($DryRun){Write-Host 'Dry-run valid: no manifest changes published.';exit 0};if((HashFile $ClosurePath)-ne$before){throw 'Closure or artifact drift detected before publication.'};$tmp="$ClosurePath.$([guid]::NewGuid().ToString('N')).tmp";try{[IO.File]::WriteAllText($tmp,($closure|ConvertTo-Json -Depth 20),[Text.UTF8Encoding]::new($false));Move-Item -LiteralPath $tmp -Destination $ClosurePath -Force}finally{Remove-Item $tmp -Force -ErrorAction SilentlyContinue}
