[CmdletBinding()]
param([Parameter(Mandatory)][string]$ClosurePath,[string]$ThreatId,[switch]$RequireSignedOff,[string]$TrustedRootPath,[string]$ReviewerPolicyPath,[ValidateSet('Text','Json')][string]$DiagnosticFormat='Text')
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
try{Add-Type -AssemblyName System.Security -ErrorAction Stop}catch{$result=[pscustomobject]@{status='execution_error';diagnostics=@();error='pkcs_runtime_unavailable'};if($DiagnosticFormat-eq'Json'){$result|ConvertTo-Json -Compress}else{[Console]::Error.WriteLine('SECURITY CLOSURE ERROR: pkcs_runtime_unavailable')};exit 2}
if(-not('Phase1Security.NativeFile' -as[type])){Add-Type -TypeDefinition @'
using System;
using System.Runtime.InteropServices;
namespace Phase1Security {
  public static class NativeFile {
    [DllImport("kernel32.dll", CharSet=CharSet.Unicode, SetLastError=true)]
    public static extern uint GetFinalPathNameByHandleW(IntPtr handle, System.Text.StringBuilder path, uint length, uint flags);
  }
}
'@}
$repoRoot=Split-Path -Parent $PSScriptRoot;$matrixPath=Join-Path $repoRoot 'evidence/phase1/requirement-matrix.yaml'
$script:Targets=@('T-01-15-01','T-01-15-02','T-01-15-03','T-01-15-04','T-01-15-06','T-01-16-01','T-01-16-02','T-01-16-03','T-01-16-04','T-01-16-06','T-01-18-SC','T-01-20-01','T-01-20-02','T-01-20-05','T-01-21-01','T-01-21-02','T-01-21-03','T-01-21-04','T-01-21-05');$script:Diagnostics=[Collections.Generic.List[object]]::new()
function Get-HashText([string]$Text){$s=[Security.Cryptography.SHA256]::Create();try{$b=[Text.UTF8Encoding]::new($false).GetBytes(($Text-replace"`r`n","`n"));([BitConverter]::ToString($s.ComputeHash($b))).Replace('-','').ToLowerInvariant()}finally{$s.Dispose()}}
function Get-HashFile([string]$Path){$s=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($s.ComputeHash([IO.File]::ReadAllBytes((Resolve-Path -LiteralPath $Path))))).Replace('-','').ToLowerInvariant()}finally{$s.Dispose()}}
function Get-HashStream([IO.Stream]$Stream){$Stream.Position=0;$s=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($s.ComputeHash($Stream))).Replace('-','').ToLowerInvariant()}finally{$s.Dispose()}}
function Get-HashBytes([byte[]]$Bytes){[byte[]]$data=[byte[]]::new(0);if($null-ne$Bytes){$data=$Bytes};$s=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($s.ComputeHash($data,0,$data.Length))).Replace('-','').ToLowerInvariant()}finally{$s.Dispose()}}
function ConvertTo-Canonical($Value){(($Value|ConvertTo-Json -Depth 20 -Compress)-replace"`r`n","`n")}
function Get-Payload($r){[ordered]@{threat_id=[string]$r.threat_id;disposition=[string]$r.disposition;severity=[string]$r.severity;mitigation_assertion=[string]$r.mitigation_assertion;implementation_refs=@($r.implementation_refs|%{[ordered]@{path=[string]$_.path;sha256=[string]$_.sha256}});evidence_attempt_ids=@($r.evidence_attempt_ids|%{[string]$_});required_machine_roles=@($r.required_machine_roles|%{[string]$_});artifact_refs=@($r.artifact_refs|%{[ordered]@{path=[string]$_.path;sha256=[string]$_.sha256;role=[string]$_.role}});procedure_version=[string]$r.procedure_version;environment_fingerprint=$r.environment_fingerprint}}
function Get-PayloadDigest($r){Get-HashText (ConvertTo-Canonical (Get-Payload $r))}
function Get-AttestationBody($a){[ordered]@{threat_id=[string]$a.threat_id;payload_digest=[string]$a.payload_digest;reviewer_identity=$a.reviewer_identity;review_utc=[string]$a.review_utc;procedure_version=[string]$a.procedure_version;environment_fingerprint=$a.environment_fingerprint;previous_attestation_digest=[string]$a.previous_attestation_digest}}
function Get-AttestationDigest($a){Get-HashText (ConvertTo-Canonical (Get-AttestationBody $a))}
function Get-HistoryEnvelopeBody($e){[ordered]@{schema_version=[string]$e.schema_version;threat_id=[string]$e.threat_id;payload_digest=[string]$e.payload_digest;history_entries=@($e.history_entries|%{[ordered]@{attestation_digest=[string]$_.attestation_digest;signature_cms_sha256=[string]$_.signature_cms_sha256}});history_count=[int]$e.history_count;latest_attestation_digest=[string]$e.latest_attestation_digest;reviewer_identity=$e.reviewer_identity;review_utc=[string]$e.review_utc;procedure_version=[string]$e.procedure_version;environment_fingerprint=$e.environment_fingerprint}}
function Get-HistoryEntries($history){@($history|%{$property=$_.PSObject.Properties['signature_cms_base64'];try{[byte[]]$bytes=if($property-and![string]::IsNullOrWhiteSpace([string]$property.Value)){[Convert]::FromBase64String([string]$property.Value)}else{[byte[]]@()}}catch{throw 'historical_signature_bytes_malformed'};[ordered]@{attestation_digest=[string]$_.attestation_digest;signature_cms_sha256=Get-HashBytes ([byte[]]$bytes)}})}
function Add-Diagnostic($Code,$Tid,$Message){$script:Diagnostics.Add([pscustomobject]@{code=$Code;threat_id=$Tid;message=$Message})}
function Resolve-RepositoryReference([string]$ChildPath){
 if([string]::IsNullOrWhiteSpace($ChildPath)-or[IO.Path]::IsPathRooted($ChildPath)){throw 'reference_path_rooted'}
 $root=[IO.Path]::GetFullPath($repoRoot).TrimEnd([IO.Path]::DirectorySeparatorChar,[IO.Path]::AltDirectorySeparatorChar)+[IO.Path]::DirectorySeparatorChar
 try{$candidate=[IO.Path]::GetFullPath((Join-Path $root $ChildPath))}catch{throw 'reference_path_invalid'}
 if(!$candidate.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)){throw 'reference_path_outside'};$candidate
}
function Open-RepositoryReference([string]$ChildPath){
 $candidate=Resolve-RepositoryReference $ChildPath
 try{$stream=[IO.FileStream]::new($candidate,[IO.FileMode]::Open,[IO.FileAccess]::Read,([IO.FileShare]::Read-bor[IO.FileShare]::Delete))}catch{throw 'reference_file_missing'}
 try{$capacity=32768;$builder=[Text.StringBuilder]::new($capacity);$length=[Phase1Security.NativeFile]::GetFinalPathNameByHandleW($stream.SafeFileHandle.DangerousGetHandle(),$builder,[uint32]$capacity,0);if($length-eq0-or$length-ge$capacity){throw 'reference_final_path_unavailable'};$final=$builder.ToString();if($final.StartsWith('\\?\UNC\',[StringComparison]::OrdinalIgnoreCase)){$final='\\'+$final.Substring(8)}elseif($final.StartsWith('\\?\',[StringComparison]::OrdinalIgnoreCase)){$final=$final.Substring(4)};$root=[IO.Path]::GetFullPath($repoRoot).TrimEnd([IO.Path]::DirectorySeparatorChar,[IO.Path]::AltDirectorySeparatorChar)+[IO.Path]::DirectorySeparatorChar;if(!$final.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)){throw 'reference_reparse_escape'};[pscustomobject]@{Stream=$stream;FinalPath=$final};$stream=$null}finally{if($stream){$stream.Dispose()}}
}
function Invoke-CustomRootChainValidation($Certificate,$Roots){
 $pwsh=Get-Command pwsh -ErrorAction SilentlyContinue|Select-Object -First 1;if(!$pwsh){throw 'custom_root_runtime_unavailable'};$dir=Join-Path ([IO.Path]::GetTempPath()) ('phase1-chain-'+[guid]::NewGuid().ToString('N'));[void][IO.Directory]::CreateDirectory($dir);$certPath=Join-Path $dir 'signer.cer';$rootPaths=@();$hadCert=Test-Path Env:PHASE1_CHAIN_CERT;$oldCert=$env:PHASE1_CHAIN_CERT;$hadRoots=Test-Path Env:PHASE1_CHAIN_ROOTS;$oldRoots=$env:PHASE1_CHAIN_ROOTS;try{[IO.File]::WriteAllBytes($certPath,$Certificate.Export([Security.Cryptography.X509Certificates.X509ContentType]::Cert));for($i=0;$i-lt$Roots.Count;$i++){$path=Join-Path $dir ("root-$i.cer");[IO.File]::WriteAllBytes($path,$Roots[$i].Export([Security.Cryptography.X509Certificates.X509ContentType]::Cert));$rootPaths+=$path};$env:PHASE1_CHAIN_CERT=$certPath;$env:PHASE1_CHAIN_ROOTS=$rootPaths-join[IO.Path]::PathSeparator;$command='$cert=[Security.Cryptography.X509Certificates.X509Certificate2]::new($env:PHASE1_CHAIN_CERT);$roots=@($env:PHASE1_CHAIN_ROOTS-split[IO.Path]::PathSeparator|%{[Security.Cryptography.X509Certificates.X509Certificate2]::new($_)});$chain=[Security.Cryptography.X509Certificates.X509Chain]::new();try{$chain.ChainPolicy.TrustMode=[Security.Cryptography.X509Certificates.X509ChainTrustMode]::CustomRootTrust;foreach($root in $roots){$null=$chain.ChainPolicy.CustomTrustStore.Add($root)};$chain.ChainPolicy.RevocationMode=[Security.Cryptography.X509Certificates.X509RevocationMode]::Online;$chain.ChainPolicy.RevocationFlag=[Security.Cryptography.X509Certificates.X509RevocationFlag]::ExcludeRoot;$chain.ChainPolicy.UrlRetrievalTimeout=[TimeSpan]::FromSeconds(15);$chain.ChainPolicy.VerificationFlags=[Security.Cryptography.X509Certificates.X509VerificationFlags]::NoFlag;$ok=$chain.Build($cert);$last=if($chain.ChainElements.Count){$chain.ChainElements[$chain.ChainElements.Count-1].Certificate.Thumbprint}else{''''};$anchored=@($roots|?{$_.Thumbprint-eq$last}).Count-gt0;[pscustomobject]@{ok=$ok;anchored=$anchored;statuses=@($chain.ChainStatus|%{[string]$_.Status})}|ConvertTo-Json -Compress}finally{$chain.Dispose();$cert.Dispose();$roots|%{$_.Dispose()}}';$encoded=[Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($command));$json=& $pwsh.Source -NoProfile -EncodedCommand $encoded;if($LASTEXITCODE-ne0-or!$json){throw 'custom_root_chain_failed'};$json|ConvertFrom-Json}finally{if($hadCert){$env:PHASE1_CHAIN_CERT=$oldCert}else{Remove-Item Env:PHASE1_CHAIN_CERT -ErrorAction SilentlyContinue};if($hadRoots){$env:PHASE1_CHAIN_ROOTS=$oldRoots}else{Remove-Item Env:PHASE1_CHAIN_ROOTS -ErrorAction SilentlyContinue};Remove-Item $dir -Recurse -Force -ErrorAction SilentlyContinue}
}
function Read-TrustInputs{
 if(!$RequireSignedOff){return $null};if(!$TrustedRootPath-or!(Test-Path -LiteralPath $TrustedRootPath)){throw 'trusted_root_missing'};if(!$ReviewerPolicyPath-or!(Test-Path -LiteralPath $ReviewerPolicyPath)){throw 'reviewer_policy_missing'}
 $roots=[Collections.Generic.List[Security.Cryptography.X509Certificates.X509Certificate2]]::new();$raw=Get-Content -Raw -LiteralPath $TrustedRootPath
 foreach($m in [regex]::Matches($raw,'-----BEGIN CERTIFICATE-----(?<b64>[\s\S]*?)-----END CERTIFICATE-----')){$roots.Add([Security.Cryptography.X509Certificates.X509Certificate2]::new([Convert]::FromBase64String(($m.Groups['b64'].Value-replace'\s',''))))};if(!$roots.Count){try{$roots.Add([Security.Cryptography.X509Certificates.X509Certificate2]::new($TrustedRootPath))}catch{throw 'trusted_root_invalid'}}
 try{$policy=Get-Content -Raw -LiteralPath $ReviewerPolicyPath|ConvertFrom-Json}catch{throw 'reviewer_policy_invalid'};$ekuProperty=$policy.PSObject.Properties['required_eku_oids'];if($policy.schema_version-ne'phase1-reviewer-policy/v1'-or!$policy.policy_id-or!$policy.procedure_version-or!$policy.reviewers-or!$ekuProperty-or!@($ekuProperty.Value).Count){throw 'reviewer_policy_invalid'};foreach($oid in @($ekuProperty.Value)){try{[void][Security.Cryptography.Oid]::new([string]$oid)}catch{throw 'reviewer_policy_invalid'}};[pscustomobject]@{Roots=$roots;Policy=$policy;Identity=(Get-HashFile $ReviewerPolicyPath)}
}
function Test-SignedAttestation($a,$tid,$trust){
 if(!$a.signature_cms_base64){Add-Diagnostic signature_missing $tid 'Detached reviewer signature is missing.';return};$bytes=[Text.UTF8Encoding]::new($false).GetBytes((ConvertTo-Canonical (Get-AttestationBody $a)))
 try{$cms=[Security.Cryptography.Pkcs.SignedCms]::new([Security.Cryptography.Pkcs.ContentInfo]::new($bytes),$true);$cms.Decode([Convert]::FromBase64String([string]$a.signature_cms_base64));$cms.CheckSignature($true)}catch{Add-Diagnostic signature_invalid $tid 'Detached reviewer signature is invalid.';return};if($cms.SignerInfos.Count-ne1){Add-Diagnostic signer_count_invalid $tid 'Exactly one signer is required.';return}
 $cert=$cms.SignerInfos[0].Certificate;$thumb=($cert.Thumbprint-replace'\s','').ToUpperInvariant();$reviewer=@($trust.Policy.reviewers|?{([string]$_.thumbprint-replace'\s','').ToUpperInvariant()-eq$thumb-and[string]$_.identity-eq[string]$a.reviewer_identity.name});if($reviewer.Count-ne1){Add-Diagnostic reviewer_not_approved $tid 'Signer thumbprint and identity are not approved.';return}
 $keyUsage=@($cert.Extensions|Where-Object {$_.Oid.Value-eq'2.5.29.15'});if($keyUsage.Count-ne1-or!(($keyUsage[0].KeyUsages-band[Security.Cryptography.X509Certificates.X509KeyUsageFlags]::DigitalSignature)-eq[Security.Cryptography.X509Certificates.X509KeyUsageFlags]::DigitalSignature)){Add-Diagnostic signer_key_usage_invalid $tid 'Signer certificate lacks digital-signature key usage.';return}
 $eku=@($cert.Extensions|Where-Object {$_.Oid.Value-eq'2.5.29.37'});$ekuValues=if($eku.Count-eq1){@($eku[0].EnhancedKeyUsages|ForEach-Object {$_.Value})}else{@()};if(@($trust.Policy.required_eku_oids|Where-Object {$_-notin$ekuValues}).Count){Add-Diagnostic signer_eku_invalid $tid 'Signer certificate lacks a policy-required EKU.';return}
 $chainResult=Invoke-CustomRootChainValidation $cert $trust.Roots;$statuses=@($chainResult.statuses);if('Revoked'-in$statuses){Add-Diagnostic signer_revoked $tid 'Signer certificate is revoked.';return};if('OfflineRevocation'-in$statuses-or'RevocationStatusUnknown'-in$statuses){Add-Diagnostic signer_revocation_indeterminate $tid 'Signer revocation status is unavailable or indeterminate.';return};if(!$chainResult.ok-or!$chainResult.anchored-or$statuses.Count){Add-Diagnostic signer_chain_untrusted $tid 'Signer does not chain cleanly to an externally trusted root.';return}
 $when=[DateTimeOffset]::MinValue;if(![DateTimeOffset]::TryParse([string]$a.review_utc,[ref]$when)){Add-Diagnostic review_time_invalid $tid 'Review timestamp is invalid.'}else{$skew=[int]$trust.Policy.max_clock_skew_seconds;if($when.UtcDateTime-lt$cert.NotBefore.ToUniversalTime().AddSeconds(-$skew)-or$when.UtcDateTime-gt$cert.NotAfter.ToUniversalTime().AddSeconds($skew)){Add-Diagnostic signer_time_invalid $tid 'Signer was not valid at review time.'};if($when.UtcDateTime-gt[DateTime]::UtcNow.AddSeconds($skew)){Add-Diagnostic review_time_future $tid 'Review timestamp exceeds allowed skew.'}}
 if([string]$a.procedure_version-ne[string]$trust.Policy.procedure_version){Add-Diagnostic procedure_not_approved $tid 'Procedure is not approved.'};if([string]$a.environment_fingerprint.machine_identity-ne[string]$reviewer[0].machine_identity-or[string]$a.environment_fingerprint.role-ne[string]$reviewer[0].role-or[string]$a.environment_fingerprint.domain_network_identity-ne[string]$reviewer[0].domain_network_identity){Add-Diagnostic reviewer_context_invalid $tid 'Reviewer machine, role, or domain is not approved.'}
}
function Test-HistoryEnvelope($r,$tid,$trust){
 $property=$r.PSObject.Properties['history_envelope'];if(!$property-or!$property.Value){Add-Diagnostic historical_signature_envelope_missing $tid 'Current historical signature envelope is missing.';return};$e=$property.Value;$history=@($r.attestations);if([string]$e.schema_version-ne'phase1-history-envelope/v1'-or[string]$e.threat_id-ne$tid-or[string]$e.payload_digest-ne[string]$r.payload_digest-or[int]$e.history_count-ne$history.Count-or[string]$e.latest_attestation_digest-ne[string]$history[-1].attestation_digest){Add-Diagnostic historical_signature_digest_mismatch $tid 'Historical signature envelope metadata does not match the ordered history.';return};try{$expected=Get-HistoryEntries $history}catch{Add-Diagnostic historical_signature_digest_mismatch $tid 'Historical signature bytes are malformed.';return};if($expected.Count-ne@($e.history_entries).Count){Add-Diagnostic historical_signature_digest_mismatch $tid 'Historical signature envelope count does not match.';return};for($i=0;$i-lt$expected.Count;$i++){if([string]$expected[$i].attestation_digest-ne[string]$e.history_entries[$i].attestation_digest-or[string]$expected[$i].signature_cms_sha256-ne[string]$e.history_entries[$i].signature_cms_sha256){Add-Diagnostic historical_signature_digest_mismatch $tid 'Historical signature bytes or order do not match the trusted envelope.';return}};if([string]$e.envelope_digest-ne(Get-HashText (ConvertTo-Canonical (Get-HistoryEnvelopeBody $e)))){Add-Diagnostic historical_signature_digest_mismatch $tid 'Historical signature envelope digest is invalid.';return};$bodyBytes=[Text.UTF8Encoding]::new($false).GetBytes((ConvertTo-Canonical (Get-HistoryEnvelopeBody $e)));try{$cms=[Security.Cryptography.Pkcs.SignedCms]::new([Security.Cryptography.Pkcs.ContentInfo]::new($bodyBytes),$true);$cms.Decode([Convert]::FromBase64String([string]$e.signature_cms_base64));$cms.CheckSignature($true)}catch{Add-Diagnostic historical_signature_envelope_invalid $tid 'Historical signature envelope signature is invalid.';return};if($cms.SignerInfos.Count-ne1){Add-Diagnostic historical_signature_envelope_invalid $tid 'Historical signature envelope must have exactly one signer.';return};$thumb=($cms.SignerInfos[0].Certificate.Thumbprint-replace'\s','').ToUpperInvariant();$reviewer=@($trust.Policy.reviewers|?{([string]$_.thumbprint-replace'\s','').ToUpperInvariant()-eq$thumb-and[string]$_.identity-eq[string]$e.reviewer_identity.name});if($reviewer.Count-ne1-or[string]$e.procedure_version-ne[string]$trust.Policy.procedure_version-or[string]$e.environment_fingerprint.machine_identity-ne[string]$reviewer[0].machine_identity-or[string]$e.environment_fingerprint.role-ne[string]$reviewer[0].role-or[string]$e.environment_fingerprint.domain_network_identity-ne[string]$reviewer[0].domain_network_identity){Add-Diagnostic historical_signature_envelope_invalid $tid 'Historical signature envelope signer context is not approved.'}
}
function Test-Record($r,$trust){
 $tid=[string]$r.threat_id;if($tid-notin$script:Targets){throw "unknown threat id $tid"};if($r.disposition-ne'mitigate'-or$r.severity-ne'high'){throw "$tid invalid disposition/severity"};$pd=Get-PayloadDigest $r;if([string]$r.payload_digest-ne$pd){Add-Diagnostic payload_digest_mismatch $tid 'Stored payload digest does not match current payload.'}
 foreach($ref in @($r.implementation_refs)+@($r.artifact_refs)){if([string]$ref.sha256-notmatch'^[a-f0-9]{64}$'){throw "$tid malformed digest"};$opened=Open-RepositoryReference ([string]$ref.path);try{if((Get-HashStream $opened.Stream)-ne[string]$ref.sha256){throw "$tid file digest mismatch $($ref.path)"}}finally{$opened.Stream.Dispose()}}
 $previous='';$seen=@{};foreach($a in @($r.attestations)){if([string]$a.threat_id-ne$tid){Add-Diagnostic attestation_threat_mismatch $tid 'Attestation threat mismatch.'};if([string]$a.previous_attestation_digest-ne$previous){Add-Diagnostic attestation_predecessor_mismatch $tid 'Predecessor invalid.'};$actual=Get-AttestationDigest $a;if([string]$a.attestation_digest-ne$actual){Add-Diagnostic attestation_digest_mismatch $tid 'Attestation digest invalid.'};if($seen.ContainsKey([string]$a.attestation_digest)){Add-Diagnostic duplicate_attestation $tid 'Duplicate attestation.'};$seen[[string]$a.attestation_digest]=$true;$previous=[string]$a.attestation_digest}
 if($RequireSignedOff){$latest=@($r.attestations)|Select-Object -Last 1;if(!$latest-or[string]$latest.payload_digest-ne$pd){Add-Diagnostic unsigned_current_attestation $tid 'No current attestation.'}else{Test-SignedAttestation $latest $tid $trust;Test-HistoryEnvelope $r $tid $trust}}
}
try{$trust=Read-TrustInputs;if(!(Test-Path -LiteralPath $ClosurePath)){throw 'closure manifest missing'};$c=Get-Content -Raw -LiteralPath $ClosurePath|ConvertFrom-Json;if($c.schema_version-ne'phase1-security-closure/v2'){throw 'unsupported closure schema version'};if((Get-HashFile $matrixPath)-ne[string]$c.matrix_digest){throw 'matrix digest mismatch'};$targets=@($c.closure_targets|Sort-Object);if($targets.Count-ne19-or@(Compare-Object ($script:Targets|Sort-Object) $targets).Count-ne0){throw 'closure target allowlist mismatch'};$by=@{};foreach($r in @($c.records)){if($by.ContainsKey([string]$r.threat_id)){throw 'duplicate record'};$by[[string]$r.threat_id]=$r};$selected=if($ThreatId){@($ThreatId)}else{$script:Targets};foreach($tid in $selected){if(!$by.ContainsKey($tid)){throw "missing record $tid"};Test-Record $by[$tid] $trust};if(!$ThreatId-and$by.Count-ne19){throw 'record count mismatch'};$md=Get-HashFile $ClosurePath;$result=[pscustomobject]@{status=if($script:Diagnostics.Count){'validation_failed'}else{'valid'};manifest_digest=$md;reviewer_policy_identity=if($trust){$trust.Identity}else{$null};diagnostics=@($script:Diagnostics)};if($DiagnosticFormat-eq'Json'){$result|ConvertTo-Json -Depth 8 -Compress}else{if($script:Diagnostics.Count){$script:Diagnostics|%{Write-Host "SECURITY CLOSURE FAILED [$($_.code)] $($_.threat_id): $($_.message)"}}else{Write-Host "Security closure valid: manifest=$md policy=$($result.reviewer_policy_identity)"}};if($script:Diagnostics.Count){exit 3}else{exit 0}}catch{$result=[pscustomobject]@{status='execution_error';diagnostics=@();error=$_.Exception.Message};if($DiagnosticFormat-eq'Json'){$result|ConvertTo-Json -Compress}else{[Console]::Error.WriteLine("SECURITY CLOSURE ERROR: $($_.Exception.Message)")};exit 2}
