[CmdletBinding()]
param([Parameter(Mandatory)][string]$ClosurePath,[string]$SecurityPath,[string]$ThreatId,[switch]$RequireSignedOff,[ValidateSet('Text','Json')][string]$DiagnosticFormat='Text')
$ErrorActionPreference='Stop'; Set-StrictMode -Version Latest
$repoRoot=Split-Path -Parent $PSScriptRoot
$matrixPath=Join-Path $repoRoot 'evidence/phase1/requirement-matrix.yaml'
$script:Targets=@('T-01-15-01','T-01-15-02','T-01-15-03','T-01-15-04','T-01-15-06','T-01-16-01','T-01-16-02','T-01-16-03','T-01-16-04','T-01-16-06','T-01-18-SC','T-01-20-01','T-01-20-02','T-01-20-05','T-01-21-01','T-01-21-02','T-01-21-03','T-01-21-04','T-01-21-05')
$script:Diagnostics=[Collections.Generic.List[object]]::new()
function Get-HashText([string]$Text){$s=[Security.Cryptography.SHA256]::Create();try{$b=[Text.UTF8Encoding]::new($false).GetBytes(($Text-replace"`r`n","`n"));([BitConverter]::ToString($s.ComputeHash($b))).Replace('-','').ToLowerInvariant()}finally{$s.Dispose()}}
function Get-HashFile([string]$Path){$s=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($s.ComputeHash([IO.File]::ReadAllBytes((Resolve-Path -LiteralPath $Path))))).Replace('-','').ToLowerInvariant()}finally{$s.Dispose()}}
function ConvertTo-Canonical($Value){(($Value|ConvertTo-Json -Depth 20 -Compress)-replace"`r`n","`n")}
function Get-Payload($r){[ordered]@{threat_id=[string]$r.threat_id;disposition=[string]$r.disposition;severity=[string]$r.severity;mitigation_assertion=[string]$r.mitigation_assertion;implementation_refs=@($r.implementation_refs|%{[ordered]@{path=[string]$_.path;sha256=[string]$_.sha256}});evidence_attempt_ids=@($r.evidence_attempt_ids|%{[string]$_});required_machine_roles=@($r.required_machine_roles|%{[string]$_});artifact_refs=@($r.artifact_refs|%{[ordered]@{path=[string]$_.path;sha256=[string]$_.sha256;role=[string]$_.role}});procedure_version=[string]$r.procedure_version;environment_fingerprint=$r.environment_fingerprint}}
function Get-PayloadDigest($r){Get-HashText (ConvertTo-Canonical (Get-Payload $r))}
function Get-AttestationDigest($a){Get-HashText (ConvertTo-Canonical ([ordered]@{threat_id=[string]$a.threat_id;payload_digest=[string]$a.payload_digest;reviewer_identity=$a.reviewer_identity;review_utc=[string]$a.review_utc;procedure_version=[string]$a.procedure_version;environment_fingerprint=$a.environment_fingerprint;previous_attestation_digest=[string]$a.previous_attestation_digest}))}
function Add-Diagnostic($Code,$Tid,$Message){$script:Diagnostics.Add([pscustomobject]@{code=$Code;threat_id=$Tid;message=$Message})}
function Test-Record($r){
 $tid=[string]$r.threat_id;if($tid-notin$script:Targets){throw "unknown threat id $tid"};if($r.disposition-ne'mitigate'-or$r.severity-ne'high'){throw "$tid invalid disposition/severity"}
 $pd=Get-PayloadDigest $r;if([string]$r.payload_digest-ne$pd){Add-Diagnostic payload_digest_mismatch $tid 'Stored payload digest does not match current protected payload.'}
 foreach($ref in @($r.implementation_refs)+@($r.artifact_refs)){if([string]$ref.sha256-notmatch'^[a-f0-9]{64}$'){throw "$tid malformed digest"};$full=Join-Path $repoRoot ([string]$ref.path);if(!(Test-Path -LiteralPath $full)){throw "$tid missing $($ref.path)"};if((Get-HashFile $full)-ne[string]$ref.sha256){throw "$tid file digest mismatch $($ref.path)"}}
 $previous='';$seen=@{};foreach($a in @($r.attestations)){if([string]$a.threat_id-ne$tid){Add-Diagnostic attestation_threat_mismatch $tid 'Attestation threat ID mismatch.'};if([string]$a.previous_attestation_digest-ne$previous){Add-Diagnostic attestation_predecessor_mismatch $tid 'Attestation predecessor link invalid.'};$actual=Get-AttestationDigest $a;if([string]$a.attestation_digest-ne$actual){Add-Diagnostic attestation_digest_mismatch $tid 'Attestation digest invalid.'};if($seen.ContainsKey([string]$a.attestation_digest)){Add-Diagnostic duplicate_attestation $tid 'Duplicate attestation.'};$seen[[string]$a.attestation_digest]=$true;$previous=[string]$a.attestation_digest}
 if($RequireSignedOff){$latest=@($r.attestations)|Select-Object -Last 1;if(!$latest-or[string]$latest.payload_digest-ne$pd){Add-Diagnostic unsigned_current_attestation $tid 'No valid latest attestation binds the current payload.'}}
}
try{
 if(!(Test-Path -LiteralPath $ClosurePath)){throw 'closure manifest missing'};$c=Get-Content -Raw -LiteralPath $ClosurePath|ConvertFrom-Json;if($c.schema_version-ne'phase1-security-closure/v2'){throw 'unsupported closure schema version'};if((Get-HashFile $matrixPath)-ne[string]$c.matrix_digest){throw 'matrix digest mismatch'}
 $targets=@($c.closure_targets|Sort-Object);if($targets.Count-ne19-or@(Compare-Object ($script:Targets|Sort-Object) $targets).Count-ne0){throw 'closure target allowlist mismatch'};$by=@{};foreach($r in @($c.records)){if($by.ContainsKey([string]$r.threat_id)){throw 'duplicate record'};$by[[string]$r.threat_id]=$r};$selected=if($ThreatId){@($ThreatId)}else{$script:Targets};foreach($tid in $selected){if(!$by.ContainsKey($tid)){throw "missing record $tid"};Test-Record $by[$tid]};if(!$ThreatId-and$by.Count-ne19){throw 'record count mismatch'}
 if($script:Diagnostics.Count){if($DiagnosticFormat-eq'Json'){[pscustomobject]@{status='validation_failed';diagnostics=@($script:Diagnostics)}|ConvertTo-Json -Depth 8 -Compress}else{$script:Diagnostics|%{Write-Host"SECURITY CLOSURE FAILED [$($_.code)] $($_.threat_id): $($_.message)"}};exit 3}
 if($DiagnosticFormat-eq'Json'){[pscustomobject]@{status='valid';diagnostics=@()}|ConvertTo-Json -Compress}elseif($RequireSignedOff){Write-Host "Security closure signed-off: $($selected.Count) target records valid"}else{Write-Host "Security closure pre-sign-off: $($selected.Count) target records structurally valid"};exit 0
}catch{if($DiagnosticFormat-eq'Json'){[pscustomobject]@{status='execution_error';diagnostics=@();error=$_.Exception.Message}|ConvertTo-Json -Compress}else{[Console]::Error.WriteLine("SECURITY CLOSURE ERROR: $($_.Exception.Message)")};exit 2}
